language: c

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt &&
      brew install sdl;
    fi
  - wget http://www.un4seen.com/files/bass24-$TRAVIS_OS_NAME.zip -O bass24.zip &&
    mkdir examples/include &&
    mkdir examples/lib &&
    unzip -d bass24 bass24.zip

script:
  - autoreconf -i &&
    mkdir build && (
      cd build &&
      ../configure --with-bass=`pwd`/../bass24 &&
      make
    )

addons:
  apt:
    packages:
      - libsdl1.2-dev
